variables:
  NODE_TAG:
    value: lts-alpine
    description: "The Docker tag to use when pulling the base `nodejs` image. Defaults to `lts-alpine` when empty."
  IMAGE_TAG:
    value: latest
    description: "Sets the name of the tag of the resulting image. Should be identical to NODE_TAG, if that was changed."
  EXTRA_ARGS:
    value: "--build-arg NODE_TAG"
    description: "Additional arguments for Kaniko. Several arguments can be added."
include:
  - project: templates/gitlab-ci-templates
    file: docker-build.gitlab-ci.yml
